export class CommonMedia {
  download: Resource = $r('app.media.download');
  downloads: Resource = $r('app.media.downloads');
  fav: Resource = $r('app.media.fav');
  filledFav: Resource = $r('app.media.filled_fav');
  next: Resource = $r('app.media.next');
  pause: Resource = $r('app.media.pause');
  previous: Resource = $r('app.media.previous');
  start: Resource = $r('app.media.start');
  background: Resource = $r('app.media.background');
  phone: Resource = $r('app.media.phone');
  startIcon: Resource = $r('app.media.startIcon');
  watch: Resource = $r('app.media.watch');
  reload: Resource = $r('app.media.reload');
}