export class CommonStrings {
  labelSettings: Resource = $r('app.string.label_settings');
  labelPlayFrom: Resource = $r('app.string.label_play_from');
  labelSearch: Resource = $r('app.string.label_search');
  labelOfflineMode: Resource = $r('app.string.label_offline_mode');
  labelPlayFromWatchWarning: Resource = $r('app.string.label_play_from_watch_warning');
  labelDownloads: Resource = $r('app.string.label_downloads');
  labelFavorites: Resource = $r('app.string.label_favorites');
  labelPrevious: Resource = $r('app.string.label_previous');
  labelDownloadsEmpty: Resource = $r('app.string.label_downloads_empty');
  labelFavoritesEmpty: Resource = $r('app.string.label_favorites_empty');
}